version: "3.8"

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - hiscox_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "odoo" ]
      interval: 10s
      retries: 5
      timeout: 5s

  odoo:
    image: odoo:18
    restart: always
    depends_on:
      db:
        condition: service_healthy
      hiscox_mock_api:
        condition: service_started
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    networks:
      - hiscox_network

    volumes:
      - "D:/Codes/odoo-18.0/custom_addons:/mnt/extra-addons"                          #  update left side with your local directory path to the file/folder
      - "D:/Codes/odoo-18.0/custom_addons/odoo.conf:/etc/odoo/odoo.conf"              #  update left side with your local directory path to the file/folder
      - "D:/Codes/odoo-18.0/custom_addons/entrypoint-odoo.sh:/entrypoint-odoo.sh"     #  update left side with your local directory path to the file/folder
    ports:
      - "8069:8069"
    entrypoint: [ "/bin/bash", "-c", "/entrypoint-odoo.sh" ]

  hiscox_mock_api:
    build: ./api
    restart: always
    networks:
      - hiscox_network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "5000:5000"

volumes:
  pg_data:

networks:
  hiscox_network:
    driver: bridge
